---
title: "data_exploration"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#environment setting
library(Hmisc)
library(data.table)
library(pastecs)
library(VIM)
```

```{r}
basic_data=read.csv('basic_data.csv')
colnames=colnames(basic_data)
col1=like(colnames,'atlas',fixed=TRUE) #'atlas'可替换为任意前缀（后缀）
col1=colnames[col1] 
data1=basic_data[,(names(basic_data) %in% col1)] 
data1=data1[,order(colnames(data1))] #按英文字母表reorder，方便查看
```

```{r}
atlas_agr_na<-basic_data[is.na(basic_data$atlas_berry_acrespth12)==TRUE,]
summary(atlas_agr_na[colnames(atlas_agr_na)%like%"atlas_berry"])
```
##按顺序

##keep:2,7,8,21,32,72,83
##追加哑变量 40
##缺失填0：18、19、31、73、74、75、81、84、85
##其他填充median,倒数第三部
##KNN:1，3，37，67，87，倒数第二部
##删除 64，68，69，71 一定要最后做





```{r}
##追加哑变量
data1$pck_fmrkt_is_null <- ifelse(is.na(data1$atlas_pct_fmrkt_anmlprod16), 1, 0)
```

```{r}
##缺失填0
zero_list_yd<-c(18,19,31,73,74,75,81,84,85)
impute_data <- function(vec, mn) {
  ifelse(is.na(vec), mn, vec)
}
for(i in zero_list_yd) {
  data1[,i]<-impute_data(data1[,i],0)
}

```


```{r}
##填充median
median_list_yd <- c(1:90)

impute_data <- function(vec, mn) {
  ifelse(is.na(vec), mn, vec)
}
for(i in median_list_yd) {
  data1[,i]<-impute_data(data1[,i],median(data1[,i], na.rm = T))
}
```

```{r}
##KNN
impute_KNN_list<-c(1,3,37,67,87)
for(i in impute_KNN_list) {
  kNN(data=data1,variable=colnames(data1)[i],k=10)
  print(paste(i,"has finished"))
}
##一行一行可以run，循环会死机报错，可能是M1的原因
```



```{r}
##删除
rm <- c(64,68,69,71)
data1 <- data1[,-rm]
```
